var sharing

diff --git a/.github/workflows/retry-job.yml b/.github/workflows/retry-job.yml
--- a/.github/workflows/retry-job.yml
+++ b/.github/workflows/retry-job.yml
@@ -18,16 +18,18 @@ jobs:
   retries:
     runs-on: ubuntu-22.04
     steps:
-    - name: run test with retries
-      env:
-        COUNTER: 0
-      uses: nick-fields/retry@v2.8.2
-      with:
-        timeout_minutes: 20
-        max_attempts: 3
-        shell: bash
-        command: |
-          echo "++NEW TRY++"
-          COUNTER=$(cat ${GITHUB_OUTPUT} | grep -E '^[0-9]{1,2}$' | tail -n1)
-          echo "COUNTER = <$COUNTER>"
-          exit 1
+    - uses: ./.github/actions/read-env-var
+    - run: env | sort
+    # - name: run test with retries
+    #   env:
+    #     COUNTER: 0
+    #   uses: nick-fields/retry@v2.8.2
+    #   with:
+    #     timeout_minutes: 20
+    #     max_attempts: 3
+    #     shell: bash
+    #     command: |
+    #       echo "++NEW TRY++"
+    #       COUNTER=$(cat ${GITHUB_OUTPUT} | grep -E '^[0-9]{1,2}$' | tail -n1)
+    #       echo "COUNTER = <$COUNTER>"
+    #       exit 1
